#!/bin/sh
#
#       update-squidguard  -  db update script for SquidGuard
#
#       Copyright 2003 Ivan E. Moore II <rkrusty at debian.org>
#       Copyright 2010-2012 Joachim Wiedorn <ad_debian at joonet.de>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License version 2 as
#       published by the Free Software Foundation.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

set -e

# check command options
if [ $# -gt 0 ]; then
  while [ -n "$*" ]; do
    case "$1" in
  	  -v|--verbose)   VERBOSE=y; VBPAR="-b"  ;;
    esac
    shift
  done
fi

CONFDIR=/etc/squid
CONFFILE=squidGuard.conf
DATADIR=
DBVFILE=

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Check all needed directories
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# check for new config directory (sg 1.5)
if test ! -e ${CONFDIR}/${CONFFILE}; then
  if test -e ${CONFDIR}guard/${CONFFILE}
  then CONFDIR=${CONFDIR}guard; fi
fi

[ ! -z $VERBOSE ] && echo "Check config directory for squidguard."  >&2
test -d ${CONFDIR} || mkdir -p ${CONFDIR}
if test ! -e ${CONFDIR}/${CONFFILE}; then
  echo "Config file $CONFDIR/$CONFFILE not found - update script stopped!" >&2
  exit 0
fi
chown proxy:proxy ${CONFDIR}/${CONFFILE}
chmod 0640 ${CONFDIR}/${CONFFILE}

# read default directories in config file
DATADIR=$(grep ^dbhome ${CONFDIR}/${CONFFILE} | cut -d' ' -f2)
DBVFILE=${DATADIR}/../dbversion

[ ! -z $VERBOSE ] && echo "Check data directory for squidguard."    >&2
test -d ${DATADIR} || mkdir -p ${DATADIR}
chown -R proxy:proxy ${DATADIR}
chmod -R 2770 ${DATADIR}

[ ! -z $VERBOSE ] && echo "Check done."  >&2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Rebuild full database
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo "Rebuild SquidGuard database - this can take a while."  >&2
su - proxy -c "squidGuard ${VBPAR} -C all"
# update info file with Berkeley DB version
squidGuard -v 2>&1 | sed "s/.*DB\ \(.*\):.*/\1/"  >${DBVFILE}
[ ! -z $VERBOSE ] && echo "Rebuild done."  >&2

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Reload squid service
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if [ -e /etc/init.d/squid3 ]; then
  invoke-rc.d squid3 force-reload
elif [ -e /etc/init.d/squid ]; then
  invoke-rc.d squid force-reload
else
  [ ! -z $VERBOSE ] && echo "No init.d script found for reloading Squid!" >&2
fi

